import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "./globals.css";
import { DarkModeProvider } from "@/Context/DarkModeContext";

export const metadata = {
  title: "IntelliHire",
  description: "Generated by IntelliHire",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <DarkModeProvider>{children}</DarkModeProvider>
      </body>
    </html>
  );
}
