import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import Script from "next/script";


export const metadata = {
  title: "IntelliHire",
  description: "Generated by IntelliHire",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>

        <Script
          id="chatbase-config"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.embeddedChatbotConfig = { chatbotId: "VZ1PwRyPj3AoVjDZHRUO1", domain: "www.chatbase.co" }`
          }}
        />
        <Script
          id="chatbase-embed"
          src="https://www.chatbase.co/embed.min.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
