"use client";
import { useContext, useState, useRef } from "react";
import { UserTokenContext } from "@/Context/UserTokenContext";
import { useUserAccount } from "@/Context/UserAccountContext";
import { API_BASE_URL } from "@/Config/apiRegistry";
import axios from "axios";
import * as signalR from "@microsoft/signalr";

export const useTestSession = (jobId) => {
  const { userToken } = useContext(UserTokenContext);
  const accountData = useUserAccount();
  const [testLogs, setTestLogs] = useState([]);
  const [isTesting, setIsTesting] = useState(false);
  const connectionRef = useRef(null);

  const addLog = (msg) => {
    setTestLogs((prev) => [...prev, msg]);
  };

  const runTest = async () => {
    setIsTesting(true);
    setTestLogs([]);
    addLog("Starting Test Flow...");
    
    addLog(`User Data: ${JSON.stringify(accountData, null, 2)}`);
    
    const token = userToken || localStorage.getItem("userToken");
    
    if (!token) {
      addLog("❌ NO TOKEN FOUND!");
      setIsTesting(false);
      return;
    }

    try {
      addLog("Checking User Dashboard for active sessions...");
      const dashboardRes = await axios.get(`${API_BASE_URL}/User/dashboard`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      addLog(`Dashboard Data: ${JSON.stringify(dashboardRes.data, null, 2)}`);
    } catch (err) {
      addLog(`Dashboard fetch error: ${err.message}`);
    }

    let currentSessionId = null;

    try {
      addLog("1. Connecting to SignalR...");
      const connection = new signalR.HubConnectionBuilder()
        .withUrl("https://intellhire.runasp.net/quizHub", {
          accessTokenFactory: () => token,
          skipNegotiation: false,
          transport: signalR.HttpTransportType.WebSockets | signalR.HttpTransportType.LongPolling
        })
        .withAutomaticReconnect()
        .build();

      connectionRef.current = connection;
      await connection.start();
      addLog("✅ SignalR connected successfully.");

      const waitForNextQuestion = (timeoutMs = 15000) => {
        return new Promise((resolve, reject) => {
          const timeout = setTimeout(() => {
            connection.off("nextQuestionReady");
            reject(new Error("Timeout waiting for nextQuestionReady"));
          }, timeoutMs);

          connection.on("nextQuestionReady", (question) => {
            clearTimeout(timeout);
            connection.off("nextQuestionReady");
            resolve(question);
          });
        });
      };

      let isInterviewFinished = false;
      connection.on("reportGenerationStarted", () => {
        addLog("✅ SignalR reportGenerationStarted received.");
        isInterviewFinished = true;
      });
      connection.on("reportReady", () => {
        addLog("✅ SignalR reportReady received. Interview complete.");
        isInterviewFinished = true;
      });

      addLog(`2. Calling StartSession API for jobId: ${jobId}`);
      let startRes;
      try {
        startRes = await axios.post(`${API_BASE_URL}/Session/StartSession/${jobId}`, null, {
          headers: { Authorization: `Bearer ${token}` }
        });
      } catch (err) {
        addLog(`❌ StartSession Error: ${err.response?.data?.message || err.message}`);
        addLog("Full Error Response: " + JSON.stringify(err.response?.data || {}));
        throw err;
      }
      
      const data = startRes.data;
      currentSessionId = typeof data === "string" ? data : (data?.SessionId || data?.sessionId || data?.id);
      addLog(`✅ StartSession success. SessionId: ${currentSessionId}`);

      let questionIndex = 0;
      while (!isInterviewFinished && questionIndex < 5) {
        addLog(`Waiting for Question #${questionIndex + 1} via SignalR...`);
        let question;
        try {
           question = await waitForNextQuestion();
        } catch (waitErr) {
           addLog(`⚠️ ${waitErr.message}. Attempting to answer anyway or breaking.`);
           break;
        }
        
        addLog(`✅ Received Question: ${JSON.stringify(question)}`);

        await new Promise(res => setTimeout(res, 2000));

        addLog(`3. Calling next API to submit answer for Question #${questionIndex + 1}...`);
        const formData = new FormData();
        formData.append("SessionId", currentSessionId);
        formData.append("QuestionId", question.id || question.questionId);
        formData.append("currentQuestionIndex", parseInt(question.index || 0));
        formData.append("UserAnswer", "This is a test answer generated by the test script.");
        formData.append("voiceFile", new Blob([], { type: "application/octet-stream" }), "empty.bin");

        try {
          await axios.post(`${API_BASE_URL}/Session/next`, formData, {
            headers: { 
              Authorization: `Bearer ${token}`,
              "Content-Type": "multipart/form-data"
            }
          });
          addLog(`✅ Answer submitted successfully.`);
        } catch (err) {
          addLog(`❌ Submit Answer Error: ${err.response?.data?.message || err.message}`);
          break;
        }
        
        questionIndex++;
      }

      if (currentSessionId) {
        addLog(`4. Calling EndSession API...`);
        try {
          await axios.post(`${API_BASE_URL}/Session/EndSession/${currentSessionId}/${jobId}`, null, {
             headers: { Authorization: `Bearer ${token}` }
          });
          addLog(`✅ EndSession success.`);
        } catch (err) {
          addLog(`❌ EndSession Error: ${err.response?.data?.message || err.message}`);
        }
      }

    } catch (globalErr) {
      addLog(`❌ Test Flow Aborted: ${globalErr.message}`);
    } finally {
      if (connectionRef.current) {
        connectionRef.current.stop();
        addLog("🛑 SignalR connection stopped.");
      }
      setIsTesting(false);
      addLog("Test Flow Finished.");
    }
  };

  return { runTest, isTesting, testLogs };
};
